export const ONBOARDING_QUESTIONS = {
  basic_profile: [
    {
      id: 1,
      question: "What is your name?",
      type: "text",
    },
    {
      id: 2,
      question: "What is your age?",
      type: "number",
    },
    {
      id: 3,
      question: "What is your current education level?",
      type: "select",
      options: ["School", "College", "University", "Other"],
    },
    {
      id: 4,
      question: "What is your current program or major?",
      type: "text",
    },
    {
      id: 5,
      question: "Which semester or year are you in?",
      type: "text",
    },
  ],
  timetable: [
    {
      id: 6,
      question: "Do you want to add your class timetable?",
      type: "boolean",
    },
    {
      id: 7,
      question: "How many courses do you have this semester?",
      type: "number",
      conditional_on: 6,
    },
    {
      id: 8,
      question: "Enter details for each course",
      type: "group",
      fields: [
        {
          name: "course_name",
          type: "text",
        },
        {
          name: "days_of_week",
          type: "multi_select",
          options: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        },
        {
          name: "start_time",
          type: "time",
        },
        {
          name: "end_time",
          type: "time",
        },
        {
          name: "location",
          type: "text",
        },
      ],
      conditional_on: 6,
    },
    {
      id: 9,
      question: "Do you have weekly labs?",
      type: "boolean",
      conditional_on: 6,
    },
    {
      id: 10,
      question: "Do you want to include travel time between home and campus?",
      type: "boolean",
    },
  ],
  daily_routine: [
    {
      id: 11,
      question: "What time do you usually wake up?",
      type: "time",
    },
    {
      id: 12,
      question: "What time do you sleep?",
      type: "time",
    },
    {
      id: 13,
      question: "Do you want the app to suggest an optimized daily routine?",
      type: "boolean",
    },
    {
      id: 14,
      question: "Select your daily habits",
      type: "multi_select",
      options: [
        "Study sessions",
        "Assignments / revision",
        "Meals",
        "Gym / workout",
        "Social time",
        "Part-time job",
        "Self-care",
        "Leisure time",
      ],
    },
    {
      id: 15,
      question: "Do you want reminders for hydration, breaks, or posture?",
      type: "boolean",
    },
  ],
  prayer_timings: [
    {
      id: 16,
      question: "Do you want to add prayer timings?",
      type: "boolean",
    },
    {
      id: 17,
      question: "How should we set prayer timings?",
      type: "select",
      options: ["Auto-detect by city", "Enter manually"],
      conditional_on: 16,
    },
    {
      id: 18,
      question: "Which prayers do you want to include?",
      type: "multi_select",
      options: ["Fajr", "Dhuhr", "Asr", "Maghrib", "Isha", "Jummah"],
      conditional_on: 16,
    },
  ],
  nutrition: [
    {
      id: 19,
      question: "What is your current goal?",
      type: "select",
      options: [
        "Lose weight",
        "Maintain weight",
        "Build muscle",
        "Improve energy",
        "Eat healthier",
        "Other",
      ],
    },
    {
      id: 20,
      question: "Do you want a personalized meal plan?",
      type: "boolean",
    },
    {
      id: 21,
      question: "What type of diet do you follow?",
      type: "select",
      options: [
        "Normal",
        "High protein",
        "Vegetarian",
        "Vegan",
        "Keto",
        "Flexible",
        "Other",
      ],
    },
    {
      id: 22,
      question: "Do you have any allergies or restrictions?",
      type: "multi_select",
      options: ["Dairy", "Gluten", "Nuts", "Eggs", "Seafood", "Other"],
    },
    {
      id: 23,
      question: "What type of meals do you usually prefer?",
      type: "select",
      options: ["Home meals", "Cafeteria meals", "Mix of both"],
    },
    {
      id: 24,
      question: "How many meals do you eat per day?",
      type: "multi_select",
      options: ["Breakfast", "Lunch", "Dinner", "Snacks"],
    },
  ],
  fitness: [
    {
      id: 25,
      question: "Do you work out?",
      type: "boolean",
    },
    {
      id: 26,
      question: "What is your workout frequency per week?",
      type: "number",
      conditional_on: 25,
    },
    {
      id: 27,
      question: "What type of training do you do?",
      type: "multi_select",
      options: ["Strength training", "Cardio", "Sports", "Yoga", "Mixed"],
      conditional_on: 25,
    },
    {
      id: 28,
      question: "Where do you train?",
      type: "select",
      options: ["Gym", "Home", "Outdoors"],
      conditional_on: 25,
    },
    {
      id: 29,
      question: "Do you want the app to generate a workout plan?",
      type: "boolean",
      conditional_on: 25,
    },
    {
      id: 30,
      question: "Do you track steps or activity levels?",
      type: "boolean",
    },
  ],
  long_term_goals: [
    {
      id: 31,
      question: "Select your academic goals",
      type: "multi_select",
      options: [
        "Improve GPA",
        "Top grades in specific courses",
        "Finish assignments on time",
        "Build stronger study habits",
        "Prepare for exams earlier",
      ],
    },
    {
      id: 32,
      question: "Select your personal goals",
      type: "multi_select",
      options: [
        "Get fit",
        "Build muscle",
        "Lose weight",
        "Improve sleep",
        "Reduce stress",
        "Better time management",
        "Learn new skills",
      ],
    },
    {
      id: 33,
      question: "Select your career goals",
      type: "multi_select",
      options: [
        "Learn coding or new tech skills",
        "Build portfolio",
        "Internships",
        "Research work",
        "Freelancing",
        "Networking",
      ],
    },
    {
      id: 34,
      question: "Do you want the app to create a roadmap for your goals?",
      type: "boolean",
    },
  ],
  notifications: [
    {
      id: 35,
      question: "What reminders do you want?",
      type: "multi_select",
      options: [
        "Classes",
        "Assignments",
        "Exams",
        "Meals",
        "Workouts",
        "Prayer",
        "Sleep",
        "Water intake",
        "Study sessions",
      ],
    },
    {
      id: 36,
      question: "Select the tone of reminders",
      type: "select",
      options: ["Soft", "Normal", "Strict", "Motivational"],
    },
    {
      id: 37,
      question: "How often should we send progress summaries?",
      type: "select",
      options: ["Daily", "Weekly", "Monthly", "Off"],
    },
  ],
};
